#!/usr/bin/env python3
"""Convert a binary RGB frame (.rgbf) into a PNG image.

Supports the RGBF header generated by capture_to_frame.py, and raw mode
when --raw/--width/--height/--pixfmt are provided.
"""

import argparse
import struct
import sys
import zlib
from pathlib import Path

from PIL import Image

MAGIC = b"RGBF"
VERSION = 1
PIXFMT_RGB332 = 1
PIXFMT_RGB565 = 2
HEADER_STRUCT = struct.Struct("<4sBBHHHII")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Convert RGB frame binary into PNG")
    p.add_argument("input", help="Input .rgbf file (or raw file when --raw is used)")
    p.add_argument("--output", "-o", help="Output png path (default: input with .png)")
    p.add_argument("--raw", action="store_true", help="Input is raw payload with no RGBF header")
    p.add_argument("--width", type=int, help="Image width for raw mode")
    p.add_argument("--height", type=int, help="Image height for raw mode")
    p.add_argument(
        "--pixfmt",
        choices=["rgb332", "rgb565"],
        help="Pixel format for raw mode",
    )
    return p.parse_args()


def load_rgbf(path: Path):
    data = path.read_bytes()
    if len(data) < HEADER_STRUCT.size:
        raise RuntimeError("File too small to contain RGBF header")

    magic, version, pixfmt, _reserved, width, height, payload_size, crc = HEADER_STRUCT.unpack(
        data[: HEADER_STRUCT.size]
    )
    if magic != MAGIC:
        raise RuntimeError("Invalid magic, this is not an RGBF frame")
    if version != VERSION:
        raise RuntimeError(f"Unsupported RGBF version {version}")
    if pixfmt not in (PIXFMT_RGB332, PIXFMT_RGB565):
        raise RuntimeError(f"Unsupported pixel format id {pixfmt}")

    payload = data[HEADER_STRUCT.size :]
    if len(payload) != payload_size:
        raise RuntimeError(f"Payload size mismatch: header={payload_size}, actual={len(payload)}")
    current_crc = zlib.crc32(payload) & 0xFFFFFFFF
    if current_crc != crc:
        raise RuntimeError(f"CRC mismatch: expected 0x{crc:08X}, got 0x{current_crc:08X}")

    return width, height, pixfmt, payload


def expand_rgb332(value: int):
    r = ((value >> 5) & 0x07) * 255 // 7
    g = ((value >> 2) & 0x07) * 255 // 7
    b = (value & 0x03) * 255 // 3
    return r, g, b


def expand_rgb565(value: int):
    r = ((value >> 11) & 0x1F) * 255 // 31
    g = ((value >> 5) & 0x3F) * 255 // 63
    b = (value & 0x1F) * 255 // 31
    return r, g, b


def payload_to_image(width: int, height: int, pixfmt: int, payload: bytes) -> Image.Image:
    if pixfmt == PIXFMT_RGB332:
        expected = width * height
        if len(payload) != expected:
            raise RuntimeError(f"RGB332 payload size mismatch: {len(payload)} != {expected}")
        pixels = [expand_rgb332(v) for v in payload]
    else:
        expected = width * height * 2
        if len(payload) != expected:
            raise RuntimeError(f"RGB565 payload size mismatch: {len(payload)} != {expected}")
        pixels = [
            expand_rgb565(struct.unpack_from("<H", payload, i)[0])
            for i in range(0, len(payload), 2)
        ]

    img = Image.new("RGB", (width, height))
    img.putdata(pixels)
    return img


def main() -> int:
    args = parse_args()
    in_path = Path(args.input)
    out_path = Path(args.output) if args.output else in_path.with_suffix(".png")

    if args.raw:
        if not args.width or not args.height or not args.pixfmt:
            raise RuntimeError("Raw mode requires --width, --height and --pixfmt")
        width = args.width
        height = args.height
        pixfmt = PIXFMT_RGB332 if args.pixfmt == "rgb332" else PIXFMT_RGB565
        payload = in_path.read_bytes()
    else:
        width, height, pixfmt, payload = load_rgbf(in_path)

    img = payload_to_image(width, height, pixfmt, payload)
    img.save(out_path)

    fmt_name = "RGB332" if pixfmt == PIXFMT_RGB332 else "RGB565"
    print(f"Wrote {out_path} from {width}x{height} {fmt_name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
